### ISSUE TITLE
Standard ML syntax in Visual Studio Code seems like not working (no coloring)

### ISSUE THREAD

**Issue by andry-tino** [textmate/standard-ml.tmbundle#6]
Hi, I installed the syntax file [CM.tmLanguage](https://raw.githubusercontent.com/textmate/standard-ml.tmbundle/master/Syntaxes/CM.tmLanguage) using `yo code`:

![image](https://cloud.githubusercontent.com/assets/6501517/14968823/47b866c8-10bf-11e6-9cf7-f07f91c43ade.png)

I moved the folder into `<user>/.vscode/extensions` and restarted Code. When I open ML files, I get a weird experience as the syntax coloring simply consists only in comments (grey) and the rest of the syntax is white. No real coloring is applied.

![image](https://cloud.githubusercontent.com/assets/6501517/14968807/33454224-10bf-11e6-8c50-ef253c271c8a.png)

I wonder... is this the way it is supposed to be (just not much coloring, sad to say) or there is some bug in the grammar?

**Comment by infininight** [comment]
The coloring I would think should be more than that but it would be up to how the theme colors the different scopes.

A short example from TextMate:

http://pastie.org/private/peukojwwyzkqaw8l6tjxta

Beyond that this would be best asked in a VSCode forum, etc.
